### ISSUE TITLE
Extensions that use emojis in their name cause traceback and potential settings reset on every launch

### ISSUE THREAD

**Issue by freecoderwaifu** [Haoming02/sd-webui-tabs-extension#8]
`UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3a8' in position 72: character maps to <undefined>`

This extension in particular uses an emoji:
https://github.com/tritant/sd-webui-creaprompt

This also seems to cause the settings reset popup to appear on every UI launch and relaunch, as disabling Creaprompt stops the settings reset popup from appearing.
 
Full traceback:
```
Traceback (most recent call last):
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\variousAI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\variousAI\stable-diffusion-webui-forge\extensions\sd-webui-tabs-extension\scripts\tabs_config.py", line 11, in write_data
    csv_file.write(data)
  File "F:\APPSNOBACKUP\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3a8' in position 72: character maps to <undefined>
```

**Comment by freecoderwaifu** [comment]
Fixed by https://github.com/Haoming02/sd-webui-tabs-extension/commit/f38a837a00bf175dafd88e843c56e0efee4fa38c, thanks.
